apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: susatos9/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SUPABASE_URL
        - name: SUPABASE_API_KEY
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SUPABASE_API_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_REFRESH_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JWT_EXPIRES_IN
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000