apiVersion: v1
kind: ConfigMap
metadata:
  name: progress-config
data:
  PORT: "3001"
  MONGO_URI: "mongodb+srv://davidneilleen:EApuMNK6CQQalJnp@cluster0.we5h8sk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DEFAULT_TIMEOUTS: "5000" # Timeout in 