apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SUPABASE_URL: https://ygsmcjlgwbipxytafqyc.supabase.co
  SUPABASE_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc21jamxnd2JpcHh5dGFmcXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODc0NTYsImV4cCI6MjA2Mzc2MzQ1Nn0.-7jABaJelFFKfMSCk52xfqBgqBVRcmnuIW6-Xl8bZes"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc21jamxnd2JpcHh5dGFmcXljIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODE4NzQ1NiwiZXhwIjoyMDYzNzYzNDU2fQ.5tbGekie2AanQefks0veLsuEWispAhs5olOPwJG4hXI"
  JWT_SECRET: "ntppn0bK0fDo8D8H9cTe0jCljo7XbDvTgTIfNTSQ1laJfegXJo/azFHo6JIhQyMim413FMlRov5iio3INBnUXQ=="
  JWT_REFRESH_SECRET: "ntppn0bK0fDo8D8H9cTe0jCljo7XbDvTgTIfNTSQ1laJfegXJo/azFHo6JIhQyMim413FMlRov5iio3INBnUXQ=="
  JWT_EXPIRES_IN: "1h"
  PORT: "3000"
  NODE_ENV: "development"