apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1 # Jumlah minimum pod dikurangi menjadi 1
  maxReplicas: 5 # Jumlah maksimum pod dikurangi menjadi 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Target penggunaan CPU dikurangi menjadi 30%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 # Target penggunaan memori ditambahkan dengan rata-rata 40%